---

- name: install dependencies
  package:
    name: tar
    state: present

- name: create prometheus user
  user:
    name: prometheus
    state: present

- name: create prometheus directories
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0744'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: get meta data
  block:
    - name: get latest release data
      uri:
        url: https://api.github.com/repos/prometheus/prometheus/releases/latest
        return_content: true
        headers:
          Accept: "application/vnd.github.v3+json"
      register: json_reponse
    - name: get prometheus version on remote
      slurp:
        src: /etc/prometheus/prometheus_version
      register: prometheus_remote_version
      ignore_errors: true

- name: get checksum
  block:
    - name: get sha256sums-file link
      set_fact:
        _sha256_uri: '{{ item.browser_download_url }}'
      when: "'sha256sums' in item.name"
      with_items: '{{ json_reponse.json.assets }}'
    - name: get checksum from github
      set_fact:
        _checksums: "{{ lookup('url', _sha256_uri, wantlist=True) | list }}"
    - name: get checksum for amd64
      set_fact:
        prometheus_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when: "'linux-amd64.tar.gz' in item"
  when: prometheus_remote_version["failed"] or prometheus_remote_version["content"] | b64decode != json_reponse.json.tag_name  # noqa 204

- name: download and install prometheus
  block:
    - name: get prometheus download link
      set_fact:
        _prometheus_uri: '{{ item.browser_download_url }}'
      when: "'linux-amd64.tar.gz' in item.name"
      with_items: '{{ json_reponse.json.assets }}'
    - name: download archive
      get_url:
        url: '{{ _prometheus_uri }}'
        dest: /tmp/prometheus-linux-amd64.tar.gz
        checksum: 'sha256:{{ prometheus_checksum }}'
        mode: '0644'
    - name: unpack archive
      unarchive:
        remote_src: true
        src: /tmp/prometheus-linux-amd64.tar.gz
        dest: /tmp
        list_files: true
      register: _unarchived
    - name: register unarchived folder
      set_fact:
        _unarchived_folder: '{{ _unarchived.files[0].split("/")[0] }}'
    - name: move prometheus binaries
      copy:
        remote_src: true
        src: '/tmp/{{ _unarchived_folder }}/{{ item }}'
        dest: '/usr/local/bin/{{ item }}'
        owner: root
        group: root
        mode: '0755'
      loop:
        - prometheus
        - promtool
    - name: move other prometheus files
      copy:
        remote_src: true
        src: '/tmp/{{ _unarchived_folder }}/{{ item }}'
        dest: /etc/prometheus/
        owner: prometheus
        group: prometheus
        mode: '0644'
        directory_mode: '0755'
      loop:
        - consoles
        - console_libraries
    - name: create initial prometheus configuration
      copy:
        remote_src: true
        src: '/tmp/{{ _unarchived_folder }}/prometheus.yml'
        dest: /etc/prometheus/
        owner: prometheus
        group: prometheus
        mode: '0644'
      when: prometheus_config_template is not truthy
    - name: clean up temp
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /tmp/prometheus-linux-amd64.tar.gz
        - '/tmp/{{ _unarchived_folder }}'
    - name: create binary version file
      template:
        src: prometheus_version.j2
        dest: /etc/prometheus/prometheus_version
        owner: prometheus
        group: prometheus
        mode: '0644'
  when: prometheus_remote_version["failed"] or prometheus_remote_version["content"] | b64decode != json_reponse.json.tag_name  # noqa 204
  notify: restart prometheus

- name: create prometheus configuration
  template:
    src: '{{ prometheus_config_template }}'
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
    owner: prometheus
    group: prometheus
  when: prometheus_config_template is truthy
  notify: restart prometheus

- name: create prometheus.env file
  copy:
    src: '{{ prometheus_env_file }}'
    dest: /etc/default/prometheus
    mode: '0644'
    owner: root
    group: root
  notify: restart prometheus

- name: copy service file
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    mode: '0644'
    owner: root
    group: root
  notify: restart prometheus

- name: start and enable prometheus
  service:
    name: prometheus
    state: started
    enabled: true
