---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: prometheus_centos_8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: prometheus_ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: prometheus_debian
    image: docker.io/pycontribs/debian
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
  inventory:
    host_vars:
      centos:
        ansible_user: ansible
      ubuntu:
        ansible_user: ansible
